# Generated by Django 2.0.2 on 2018-03-03 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First', models.CharField(max_length=30)),
                ('Last', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_number', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Topic'),
        ),
    ]
